### ISSUE TITLE
Create new apartment component

### ISSUE THREAD

**Issue by StephenVNelson** [StephenVNelson/strathmore-veteran-apartments#17]
# Only work off of the apartment-components branch!!!

The idea is to start by making this a reality
![image](https://user-images.githubusercontent.com/20952309/92626719-285a5b00-f27f-11ea-9357-94a71cb5780c.png)

#### Task list
- [x] Create a simple apartment component that just has a box with a photo on the left and the price on the right. 
- [ ] Create RoommateGroupAtAGlance.js component to show those little guys.
- [ ] Update RoommateGroupAtAGlance.js to be able to handle multiple roommate groups and will add arrows wherever needed for the number of roommateGroups
- [ ] Create robust tests for apartment filtering that will remove apartments that .... wait. We're no longer removing apartments! hmmmm
- [ ] Create RoommateCounter.js component to generate text like "1/3 roommates filled"
- [ ] Refine styling for components
- [x] Turn the small image into a component that has the unit number in the corner.
